# do not change anything from here
relativeURLs: false
metaDataFormat: json
#sitemap currently disabled until we find good solution to split it into parts less than 50000
disableKinds: ["RSS"]
taxonomies:
  category: "categories"
permalinks:
  products: /p/:slug/
  #I'll kill you personally if you change this setting! I've spent whole day to get it work! Compatible with hugo 0.31.1
  categories: /pc/:slug/
# you can make changes starting from here

baseurl: 'https://vex-hugo-rvy6x.ondigitalocean.app/'
homepage: 'https://vex-hugo-rvy6x.ondigitalocean.app'
title: 'Products site'
theme: 'vex-hugo'
defaultContentLanguage: 'se'
markup:
  goldmark:
    renderer:
      unsafe: true

########################### Default parameters ##########################
params:
  logo: 'images/logo.png'
  logo_width: '100px'
  # Meta data
  description: 'This is meta description'
  author: 'Denys Kyselov'
  # currency
  currency: '$'
  # contact form action
  contact_form_action: '#' # contact form works with https://formspree.io
  paginate: 24
  # snipcart public api key
  snipcart_api: "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
  # Preloader
  preloader:
    enable: true
    preloader: ''  # use .png , .svg or .gif format
  # Subscription
  subscription:
    # mailchimp subsciption
    mailchimp_form_action: 'https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074' # replace this url with yours
    mailchimp_form_name: 'b_463ee871f45d2d93748e77cad_a0a2c6d074' # replace this code with yours
  #################################### Plugins ##########################################
  plugins:
    css:
      - link: https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themefisher-font/themefisher-font.min.css
      - link: plugins/slick/slick.min.css
    js:
      - link: plugins/jquery/jquery.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
###################################### Navigation ######################################
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Products
      url: products
      weight: 2
    - name: Blog
      url: blog
      weight: 3
    - name: Review
      pre: '#'
      url: testimonial
      weight: 4
    - name: Contact
      url: contact
      weight: 5
  footer:
    - name: Blog
      url: blog
      weight: 1
    - name: Contact
      url: contact
      weight: 2
    - name: Terms & Conditions
      url: terms-conditions
      weight: 3
    - name: Privacy Policy
      url: privacy-policy
      weight: 4

########################### Default parameters ##########################
Languages:
  en:
    languageName: En
    languageCode: en-us
    contentDir: content
    weight: 1
    copyright: Developed by /dev/hands
  se:
    languageName: Se
    languageCode: sv-se
    contentDir: content
    weight: 2
    copyright: Utvecklad av /dev/hands


